/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peridot.GUI;

import peridot.GUI.component.Dialog;
import peridot.GUI.panel.NewAnalysisPanel;
import peridot.GUI.dialog.NewExpressionDialog;
import java.awt.Component;
import java.awt.Window;
import java.util.HashSet;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import peridot.RNASeq;


/**
 *
 * @author pentalpha
 */
public class NewAnalysisGUI extends Dialog {
    
    private java.awt.Frame parentFrame;
    JPanel analysisPanel;
    /**
     * Creates new form newAnalysisGUI
     */
    public NewAnalysisGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        parentFrame = parent;
        
        initComponents();
        HashSet<String> packs = new HashSet<String>();
        packs.add("edgeR");
        packs.add("DESeq");
        packs.add("EBSeq");
        analysisPanel = new NewAnalysisPanel(parent);
        this.getContentPane().add(analysisPanel,
                                  new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0,
                                                                                   this.getPreferredSize().width,
                                                                                   this.getPreferredSize().height)
                                  );
        this.getContentPane().revalidate();
        this.getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate New Analysis");
        setModal(true);
        setName("newAnalysisDialog"); // NOI18N
        setPreferredSize(new java.awt.Dimension(546, 495));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewAnalysisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewAnalysisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewAnalysisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewAnalysisGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewAnalysisGUI dialog = new NewAnalysisGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
