/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peridot.GUI.dialog;

import peridot.GUI.component.Dialog;
import java.io.File;
import peridot.GUI.panel.ViewResultsPanel;

/**
 *
 * @author Pitágoras Alves
 */
public class ScriptResultsDialog extends Dialog {
    ViewResultsPanel results;
    /**
     * Creates new form ScriptResultsViewerDialog
     */
    public ScriptResultsDialog(java.awt.Frame parent, boolean modal, String scriptName, File resultsDir) {
        super(parent, modal);
        initComponents();
        setTitle(scriptName + " results");
        results = new ViewResultsPanel(scriptName, resultsDir, false);
        this.getContentPane().add(results);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
