/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peridot.GUI.dialog;

import peridot.GUI.component.Dialog;
import peridot.GUI.component.Button;
import peridot.GUI.panel.ParametersPanel;
import peridot.AnalysisParameters;
import peridot.GUI.panel.ParametersPanel;

/**
 *
 * @author pentalpha
 */
public class SpecificParametersDialog extends Dialog {
    public ParametersPanel parametersPanel;
    /**
     * Creates new form SpecificParametersPanel
     */
    public SpecificParametersDialog(java.awt.Frame parent, boolean modal, 
            AnalysisParameters initialValues, String title) {
        super(parent, modal);
        this.setTitle(title);
        initComponents();
        parametersPanel = new ParametersPanel(initialValues, true);
        add(parametersPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                0, 0, this.getMinimumSize().width, this.getMinimumSize().height));
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 120));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
