/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package peridot.GUI.panel;
import peridot.GUI.component.Label;
import peridot.GUI.component.Panel;
/**
 *
 * @author pentalpha
 */
public class ColumnPanel extends Panel {
    private int number;
    private String name;
    private javax.swing.JLabel displayLabel;
    /**
     * Creates new form columnPanel
     */
    public ColumnPanel(int number, String name) {
        super();
        
        displayLabel = new Label();

        setMaximumSize(new java.awt.Dimension(120, 29));
        setMinimumSize(new java.awt.Dimension(120, 29));
        setPreferredSize(new java.awt.Dimension(120, 29));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
        
        displayLabel.setText("jLabel1");
        add(displayLabel);
        
        this.number = number;
        this.setName(name);
    }
    
    public void setName(String text){
        name = text;
        displayLabel.setText(Integer.toString(number) + " - " + name);
    }
    
    public String getName(){
        return name;
    }
    
    public int getNumber(){
        return number;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(new java.awt.Dimension(120, 29));
        setMinimumSize(new java.awt.Dimension(120, 29));
        setPreferredSize(new java.awt.Dimension(120, 29));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        setLayout(flowLayout1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
